# Generated by Django 5.0 on 2024-01-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='poster',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
