# Generated by Django 5.0 on 2024-01-28 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website_app', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_website_app.category'),
        ),
        migrations.AlterField(
            model_name='show',
            name='poster',
            field=models.ImageField(blank=True, upload_to='images/shows'),
        ),
    ]
