# Generated by Django 5.0 on 2024-01-28 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website_app', '0005_show_category_alter_show_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_website_app.category'),
        ),
    ]
