# Generated by Django 5.0.2 on 2024-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website_app', '0010_subscriberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='video',
            field=models.FileField(null=True, upload_to='videos'),
        ),
    ]
