# Generated by Django 5.0.4 on 2024-04-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_website_app', '0012_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
