# Generated by Django 5.0.4 on 2024-04-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_website_app', '0013_delete_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={},
        ),
        migrations.RemoveField(
            model_name='folder',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='show',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='show',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='show',
            name='seasons',
        ),
    ]
